version: '2'

services:
  web:
    image: nginx:latest
    container_name: parser_web
    ports:
      - "8090:90"
    volumes:
      - ./parser:/parser
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - parser
  php:
    container_name: parser_php
    build:
      context: ""
      dockerfile: Dockerfile
    volumes:
      - ./parser:/parser
    networks:
      - parser
  postgres:
    container_name: parser_postgres
    image: postgres:11
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - parser
    volumes:
      - ./postgres/:/var/lib/postgresql/data

networks:
  parser:
    driver: bridge